### PR TITLE
Updated tools

### PR DESCRIPTION
**Pull request by ccedmendoza**
Still need to check some tools, trinity for example

### CODE REVIEW

**Comment by ccedmendoza** [comment]
- [x] Check Trinity version to install
- [x] Check the column_regex_substitution tool by blankenber (it's newer than galaxyp's)

**Comment by drosofff** [comment]
@ccedmendoza Cedric I also saw yesterday (when I tested the metavisitor deployment) that there are still minor bugs with blast (version not consistent in the workflow), and also that few tools have been updated.

**Comment by ccedmendoza** [comment]
@drosofff Yes that's why I thought we could make this update the last one and say pin these versions as the metavisitor2 release versions. Then update the workflows and doc and finally release it.

**Comment by drosofff** [comment]
I am fine with this plan. I know that tools never end upgrading...

**Comment by ccedmendoza** [comment]
Tried the latest trinity version of the iuc, and the boolean to set and unset the pooling seems to work

**Comment by ccedmendoza** [comment]
I will keep galaxyp's version of regex_find_and_replace it has both column and not column ragex find and replace and blankenberg's only has the column one.

**Comment by drosofff** [comment]
@ccedmendoza I guess the workflows should be updated if you upgraded tools, shouldn't it ?

**Pull request closed without merging**
