### PR TITLE
The type of matching wasn't the same as in metavisitor1

### PR DESCRIPTION
**Pull request by ccedmendoza**
Changed sr_bowtie matching from "Match and report all valid alignments" to "Match on DNA, multiple mappers randomly matched at a single position"

### CODE REVIEW

**Comment by drosofff** [comment]
@ccedmendoza is this branch dead ?

**Comment by drosofff** [comment]
Ping @ccedmendoza

**Comment by ccedmendoza** [comment]
@drosofff No the changes need to be done I'm just waiting for Metavisitor2 to be updated to Galaxy 18.05 to do a last round of tool updating and releasing

**Comment by ccedmendoza** [comment]
done in branch metavisitor2

**Pull request closed without merging**
